# Python program for CCDciel
# see: https://www.ap-i.net/ccdciel/en/documentation/jsonrpc_reference

# UVEX4 list information from all the available switch

from ccdciel import ccdciel
from alpaca import management
from uvex4alpaca import *
import configparser
import sys
import os

# current script directory
scriptdir = os.path.dirname(os.path.abspath(sys.argv[0]))
# read server IP:port from config
try:
  config = configparser.ConfigParser()
  config.read(os.path.join(scriptdir,'UVEX4_Server.config'))
  uvex4server=config['Default']['Server']
except Exception as ex:
  print('Server configuration not found. Please run UVEX4_Discovery')
  sys.exit(1)


try :
    print('UVEX4 IP: '+uvex4server)   
    desc=management.description(uvex4server)
    print('Name: '+ desc['ServerName'])
    print('Manufacturer: '+ desc['Manufacturer'])
    print('Version: '+ desc['ManufacturerVersion'])
    print()

    uvex4 = UVEX4(uvex4server,0)
    uvex4.Connected=True
    
    for i in range(uvex4.MaxSwitch):
      name=uvex4.GetSwitchName(i)
      val=uvex4.GetSwitchValue(i)
      print(name+' '+f"{val}")


except Exception as ex:
    print('Error: '+type(ex).__name__,'-',ex)
    sys.exit(1)

