# This script open the telescope cover
# Require a CoverCalibrator driver

from ccdciel import ccdciel;
import sys

txt = ccdciel('calibratorstatus')['result']
if txt=='Ready':
  print('Calibrator light is not off')
  sys.exit(1)

# Open cover
resp = ccdciel('COVER_OPEN')['result']['status']
if resp!='OK!':
   sys.exit(1)

# Show status
txt = ccdciel('coverstatus')['result']
ccdciel('logMsg','Cover is now '+txt)

