#  This script unpark the telescope mount

from ccdciel import ccdciel
import sys

connected = (ccdciel('Telescope_Connected')['result'])
if not connected :
   ccdciel('LogMsg','Telescope not connected!')
   sys.exit(1)
   
parked = (ccdciel('Telescope_Parked')['result'])
if not parked :
   ccdciel('LogMsg','Telescope already unparked')
   sys.exit(0)

r = (ccdciel('Telescope_Park',False)['result']['status'])
ccdciel('LogMsg','Telescope Park %r' %(r))
